config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  devise_for :users
  resources :teste_devices
  
  root to: "page#index"


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teste_device.rb
class TesteDevice < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!
  def index
  
  end
end

app/controllers/teste_devices_controller.rb
class TesteDevicesController < ApplicationController
  before_action :set_teste_device, only: [:show, :edit, :update, :destroy]

  # GET /teste_devices
  # GET /teste_devices.json
  def index
    @teste_devices = TesteDevice.all
  end

  # GET /teste_devices/1
  # GET /teste_devices/1.json
  def show
  end

  # GET /teste_devices/new
  def new
    @teste_device = TesteDevice.new
  end

  # GET /teste_devices/1/edit
  def edit
  end

  # POST /teste_devices
  # POST /teste_devices.json
  def create
    @teste_device = TesteDevice.new(teste_device_params)

    respond_to do |format|
      if @teste_device.save
        format.html { redirect_to @teste_device, notice: 'Teste device was successfully created.' }
        format.json { render :show, status: :created, location: @teste_device }
      else
        format.html { render :new }
        format.json { render json: @teste_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teste_devices/1
  # PATCH/PUT /teste_devices/1.json
  def update
    respond_to do |format|
      if @teste_device.update(teste_device_params)
        format.html { redirect_to @teste_device, notice: 'Teste device was successfully updated.' }
        format.json { render :show, status: :ok, location: @teste_device }
      else
        format.html { render :edit }
        format.json { render json: @teste_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teste_devices/1
  # DELETE /teste_devices/1.json
  def destroy
    @teste_device.destroy
    respond_to do |format|
      format.html { redirect_to teste_devices_url, notice: 'Teste device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teste_device
      @teste_device = TesteDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teste_device_params
      params.require(:teste_device).permit(:teste)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/teste_devices_helper.rb
module TesteDevicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <head>
    <title>AulaBack2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
    <%= link_to 'Encerrar sessão', destroy_user_session_path, method: :delete, class: 'button'%>
    </header>

    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/teste_devices/_form.html.erb
<%= form_with(model: teste_device, local: true) do |form| %>
  <% if teste_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teste_device.errors.count, "error") %> prohibited this teste_device from being saved:</h2>

      <ul>
      <% teste_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :teste %>
    <%= form.text_area :teste %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teste_devices/edit.html.erb
<h1>Editing Teste Device</h1>

<%= render 'form', teste_device: @teste_device %>

<%= link_to 'Show', @teste_device %> |
<%= link_to 'Back', teste_devices_path %>

app/views/teste_devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teste Devices</h1>

<table>
  <thead>
    <tr>
      <th>Teste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teste_devices.each do |teste_device| %>
      <tr>
        <td><%= teste_device.teste %></td>
        <td><%= link_to 'Show', teste_device %></td>
        <td><%= link_to 'Edit', edit_teste_device_path(teste_device) %></td>
        <td><%= link_to 'Destroy', teste_device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teste Device', new_teste_device_path %>

app/views/teste_devices/new.html.erb
<h1>New Teste Device</h1>

<%= render 'form', teste_device: @teste_device %>

<%= link_to 'Back', teste_devices_path %>

app/views/teste_devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teste:</strong>
  <%= @teste_device.teste %>
</p>

<%= link_to 'Edit', edit_teste_device_path(@teste_device) %> |
<%= link_to 'Back', teste_devices_path %>